/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * The package com.turankanbur.calculator contains classes related to the calculator application.
 */
package com.turankanbur.calculator;

import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 * @brief This class represents the Add Ingredient Menu GUI for adding new
 *        ingredients to the database.
 */
public class AddIngredientMenu extends javax.swing.JFrame {

	/**
	 * The serial version UID for serialization.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * The name of the ingredient.
	 */
	public String ingredient_name;

	/**
	 * The price of the ingredient.
	 */
	public String ingredient_price;

	/**
	 * The database facade for adding ingredients.
	 */
	DBFacadeAddIng databaseFacade = new DBFacadeAddIng();

	/**
	 * @brief Constructor for AddIngredientMenu. Initializes the database connection
	 *        and creates the ingredient table if it doesn't exist.
	 */
	public AddIngredientMenu() {
		setResizable(false);
		databaseFacade.createIngredientTable();
		initComponents();
	}

	/**
	 * @brief This method is called from within the constructor to initialize the
	 *        form. WARNING: Do NOT modify this code. The content of this method is
	 *        always regenerated by the Form Editor.
	 */
	public void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newfoodbackground.png"))); // NOI18N
		jLabel1.setText("jLabel1");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(98, 98, 98)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE));

		jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		jLabel2.setText("Add Ingredient Menu");

		jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel3.setText("Ingredient Name");

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel4.setText("Ingredient Price");

		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jButton1.setText("Add");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jButton2.setText("Back");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 385, GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(
										layout.createSequentialGroup()
												.addPreferredGap(ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
												.addComponent(
														jLabel2, GroupLayout.PREFERRED_SIZE, 185,
														GroupLayout.PREFERRED_SIZE)
												.addGap(99))
								.addGroup(layout
										.createSequentialGroup().addGap(78)
										.addGroup(layout.createParallelGroup(Alignment.LEADING)
												.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
														.addComponent(jTextField1)
														.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 122,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 104,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextField2, GroupLayout.DEFAULT_SIZE, 155,
																Short.MAX_VALUE))
												.addGroup(layout.createSequentialGroup().addComponent(jButton1)
														.addGap(49).addComponent(jButton2, GroupLayout.PREFERRED_SIZE,
																105, GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(41, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addGap(44)
						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE).addGap(18)
						.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(29).addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
						.addGap(18)
						.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(26)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE))
						.addContainerGap(133, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
		setLocationRelativeTo(null);
	}

	/**
	 * @brief Action performed when the jTextField1 component triggers an action
	 *        event.
	 * @param evt The action event triggered by jTextField1.
	 */
	public void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed

		ingredient_name = jTextField1.getText();
	}

	/**
	 * @brief Action performed when the jTextField2 component triggers an action
	 *        event.
	 * @param evt The action event triggered by jTextField2.
	 */
	public void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed

		ingredient_price = jTextField2.getText();
	}// GEN-LAST:event_jTextField2ActionPerformed

	/**
	 * @brief Action performed when the jButton1 component (Add button) triggers an
	 *        action event.
	 * @param evt The action event triggered by jButton1.
	 */
	public void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		ingredient_name = jTextField1.getText();
		ingredient_price = jTextField2.getText();

	
		if (ingredient_name == null || ingredient_name.trim().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Ingredient name cannot be empty.", "Validation Error",
					JOptionPane.ERROR_MESSAGE);
			return;
		}

		if (ingredient_price == null || ingredient_price.trim().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Ingredient price cannot be empty.", "Validation Error",
					JOptionPane.ERROR_MESSAGE);
			return;
		}

		
		databaseFacade.addIngredientToDatabase(ingredient_name, ingredient_price);
	}

	/**
	 * @brief Action performed when the jButton2 component (Back button) triggers an
	 *        action event.
	 * @param evt The action event triggered by jButton2.
	 */
	public void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		IngredientMenu ingredientMenu = new IngredientMenu();
		ingredientMenu.setVisible(true);
		this.dispose();

	}


	/**
	 * The button for action 1.
	 */
	public javax.swing.JButton jButton1;

	/**
	 * The button for action 2.
	 */
	public javax.swing.JButton jButton2;

	/**
	 * The label 1.
	 */
	public javax.swing.JLabel jLabel1;

	/**
	 * The label 2.
	 */
	public javax.swing.JLabel jLabel2;

	/**
	 * The label 3.
	 */
	public javax.swing.JLabel jLabel3;

	/**
	 * The label 4.
	 */
	public javax.swing.JLabel jLabel4;

	/**
	 * The panel.
	 */
	public javax.swing.JPanel jPanel1;

	/**
	 * The text field 1.
	 */
	javax.swing.JTextField jTextField1;

	/**
	 * The text field 2.
	 */
	public javax.swing.JTextField jTextField2;


}
