/**
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * The package com.turankanbur.calculator contains classes related to the calculator application.
 */
package com.turankanbur.calculator;

import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 * @brief This class represents the Create Meal Menu GUI for managing and
 *        creating meals.
 */
public class CreateMealMenu extends javax.swing.JFrame {

	/**
	 * The serial version UID for serialization.
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * The database facade for creating meals.
	 */
	DBFacadeCreateMeal databaseFacadeForCreateMealMenu;

	/**
	 * @brief Constructor for CreateMealMenu. Initializes the database connection
	 *        and sets up the meal and meal recipes tables.
	 */
	public CreateMealMenu() {
		databaseFacadeForCreateMealMenu = new DBFacadeCreateMeal(this);
		setResizable(false);
		setTitle("Recipe Cost Menu");
		initComponents();
		setLocationRelativeTo(null);
		databaseFacadeForCreateMealMenu.createMealTable();
		databaseFacadeForCreateMealMenu.createMealRecipesTable();
	}

	/**
	 * @brief This method is called from within the constructor to initialize the
	 *        form. WARNING: Do NOT modify this code. The content of this method is
	 *        always regenerated by the Form Editor.
	 */
	private void initComponents() {
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton2 = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable3 = new javax.swing.JTable();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton3 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jButton4 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jTextField4 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setText("Fetch");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTable1.setModel(new DefaultTableModel(
				new Object[][] { { null, null, null }, { null, null, null }, { null, null, null }, { null, null, null },
						{ null, null, null }, { null, null, null }, { null, null, null }, { null, null, null },
						{ null, null, null }, { null, null, null }, { null, null, null }, { null, null, null },
						{ null, null, null }, { null, null, null }, { null, null, null }, { null, null, null },
						{ null, null, null }, { null, null, null }, { null, null, null }, { null, null, null },
						{ null, null, null }, { null, null, null }, { null, null, null }, { null, null, null },
						{ null, null, null }, { null, null, null }, { null, null, null }, },
				new String[] { "Recipe ID", "Recipe Name", "Recipe Price" }));
		jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
			public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
			}

			public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
				jTable1InputMethodTextChanged(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);
		jTable1.getAccessibleContext().setAccessibleName("");

		jButton2.setActionCommand("Add Recipe To Table");
		jButton2.setText("Add Recipe To Table");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jTable3.setModel(
				new DefaultTableModel(
						new Object[][] { { null }, { null }, { null }, { null }, { null }, { null }, { null }, { null },
								{ null }, { null }, { null }, { null }, { null }, { null }, { null }, { null },
								{ null }, { null }, { null }, { null }, { null }, { null }, { null }, { null },
								{ null }, { null }, { null }, { null }, { null }, { null }, },
						new String[] { "Cost For Recipes" }));
		jScrollPane2.setViewportView(jTable3);

		jTable2.setModel(
				new DefaultTableModel(
						new Object[][] { { null, null }, { null, null }, { null, null }, { null, null }, { null, null },
								{ null, null }, { null, null }, { null, null }, { null, null }, { null, null },
								{ null, null }, { null, null }, { null, null }, { null, null }, { null, null },
								{ null, null }, { null, null }, { null, null }, { null, null }, { null, null },
								{ null, null }, { null, null }, { null, null }, { null, null }, { null, null },
								{ null, null }, { null, null }, { null, null }, { null, null }, { null, null }, },
						new String[] { "Recipe-ID", "Recipe-Name" }));
		jScrollPane3.setViewportView(jTable2);

		jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24));
		jLabel2.setText("Create Meal Menu");

		jLabel3.setText("Quantity");

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jButton3.setText("Calculate Cost");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jLabel4.setText("Meal Name");

		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		jButton4.setText("CREATE MEAL");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton6.setText("Back");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton7.setText("Calculate Total Cost");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		panel = new JPanel();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addGap(2).addComponent(panel, GroupLayout.PREFERRED_SIZE, 391, GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(Alignment.TRAILING).addGroup(layout.createSequentialGroup()
						.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
						.addGap(18)
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(28).addComponent(jLabel3,
										GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE))
								.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE).addGap(
								24)
						.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
								.addComponent(jButton6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jTextField2, Alignment.LEADING)
								.addComponent(jButton4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton7, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(Alignment.LEADING,
										layout.createSequentialGroup().addGap(10).addComponent(jLabel4,
												GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE))
								.addComponent(jTextField4, Alignment.LEADING)))
						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 281, GroupLayout.PREFERRED_SIZE))
				.addGap(61)
				.addGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
						.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 258, GroupLayout.PREFERRED_SIZE).addGap(18)
						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE))
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 438, GroupLayout.PREFERRED_SIZE))
				.addGap(118)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE).addGap(56)
				.addGroup(layout.createParallelGroup(Alignment.TRAILING).addGroup(layout.createSequentialGroup()
						.addComponent(jButton7, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE).addGap(18)
						.addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
						.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE).addGap(18)
						.addComponent(jButton6, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE).addGap(65))
						.addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
						.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
				.addGap(184)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE))
				.addGap(100))
				.addGroup(layout.createSequentialGroup()
						.addComponent(panel, GroupLayout.PREFERRED_SIZE, 910, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGap(174)
						.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(18).addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(630, Short.MAX_VALUE)));

		JLabel lblNewLabel = new JLabel("");
		lblNewLabel.setVerticalAlignment(SwingConstants.TOP);
		lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);

		panel.add(lblNewLabel);
		lblNewLabel.setIcon(new ImageIcon(getClass().getResource("/mealbackground.jpg")));
		getContentPane().setLayout(layout);

		pack();
	}

	/**
	 * @brief Fetches data for recipes from the database.
	 * @param evt The event that triggers this method.
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		databaseFacadeForCreateMealMenu.FetchDataRecipes();
	}

	/**
	 * @brief Adds a selected recipe to the meal table.
	 * @param evt The event that triggers this method.
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		databaseFacadeForCreateMealMenu.addRecipeToTable();
	}

	/**
	 * @brief Navigates back to the Plan Meal Menu.
	 * @param evt The event that triggers this method.
	 */
	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		PlanMealMenu mealMenu = new PlanMealMenu();
		mealMenu.setVisible(true);
		this.dispose();
	}

	private void jTable1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
		// This method is intentionally left empty
	}

	/**
	 * @brief Calculates the cost of a selected recipe.
	 * @param evt The event that triggers this method.
	 */
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		databaseFacadeForCreateMealMenu.calculateCost();
	}

	/**
	 * @brief Adds the created meal to the database.
	 * @param evt The event that triggers this method.
	 */
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		databaseFacadeForCreateMealMenu.addMealToDatabase();
	}

	/**
	 * @brief Enter the meal name.
	 * @param evt
	 */
	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// This method is intentionally left empty
	}

	/**
	 * @brief Enter the quantity.
	 * @param evt
	 */
	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// This method is intentionally left empty
	}

	/**
	 * @brief Calculates the total cost of all added recipes.
	 * @param evt The event that triggers this method.
	 */
	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		databaseFacadeForCreateMealMenu.calculateTotalCost();
	}

	
	/**
	 * Button 1.
	 */
	public javax.swing.JButton jButton1;

	/**
	 * Button 2.
	 */
	public javax.swing.JButton jButton2;

	/**
	 * Button 3.
	 */
	public javax.swing.JButton jButton3;

	/**
	 * Button 4.
	 */
	public javax.swing.JButton jButton4;

	/**
	 * Button 6.
	 */
	public javax.swing.JButton jButton6;

	/**
	 * Button 7.
	 */
	public javax.swing.JButton jButton7;

	/**
	 * Label 2.
	 */
	public javax.swing.JLabel jLabel2;

	/**
	 * Label 3.
	 */
	public javax.swing.JLabel jLabel3;

	/**
	 * Label 4.
	 */
	public javax.swing.JLabel jLabel4;

	/**
	 * ScrollPane 1.
	 */
	public javax.swing.JScrollPane jScrollPane1;
	
	/**
	 * Table 1.
	 */
	public javax.swing.JTable jTable1;

	/**
	 * ScrollPane 2.
	 */
	public javax.swing.JScrollPane jScrollPane2;
	
	/**
	 * Table 2.
	 */
	public javax.swing.JTable jTable2;

	/**
	 * ScrollPane 3.
	 */
	public javax.swing.JScrollPane jScrollPane3;
	
	/**
	 * Table 3.
	 */
	public javax.swing.JTable jTable3;

	/**
	 * Text field 1.
	 */
	public javax.swing.JTextField jTextField1;

	/**
	 * Text field 2.
	 */
	public javax.swing.JTextField jTextField2;

	/**
	 * Text field 4.
	 */
	public javax.swing.JTextField jTextField4;

	/**
	 * Panel.
	 */
	public JPanel panel;


}
