/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * The package com.turankanbur.calculator contains classes related to the calculator application.
 */
package com.turankanbur.calculator;

import javax.swing.*;
import java.sql.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * This class represents the GUI form for the ListEditAndRemoveIngredient Menu.
 */
public class LERIngMenu extends javax.swing.JFrame {

	/**
	 * The serial version UID for serialization.
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * Represents a connection to a database.
	 */
	public Connection conn;

	/**
	 * Represents the name of the ingredient.
	 */
	public String ingredient_name;

	/**
	 * Represents the price of the ingredient.
	 */
	public String ingredient_price;


	DBFacadeLERIng databaseFacadeForListEditAndRemoveIngredientMenu;

	/**
	 * Constructor to initialize the ListEditAndRemoveIngredientMenu GUI.
	 */
	public LERIngMenu() {
		databaseFacadeForListEditAndRemoveIngredientMenu = new DBFacadeLERIng(this);
		setResizable(false);
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	public void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jButton2 = new javax.swing.JButton();
		backbutton = new javax.swing.JButton();
		EditButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Recipe Cost Calculator");

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newfoodbackground.png"))); // NOI18N
		jLabel1.setText("jLabel1");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(98, 98, 98)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE));

		jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
		jLabel2.setText("   Ingredient List");

		jTable2.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null } },
				new String[] { "ID", "Name", "Price" }));
		jTable2.setCellSelectionEnabled(true);
		jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jTable2.setDropMode(javax.swing.DropMode.ON_OR_INSERT_COLS);
		jTable2.setName(""); // NOI18N
		jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
		jTable2.setUpdateSelectionOnSort(false);
		jTable2.setVerifyInputWhenFocusTarget(false);
		jScrollPane2.setViewportView(jTable2);

		jButton2.setText("Fetch");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		backbutton.setText("Back");
		backbutton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backbuttonActionPerformed(evt);
			}
		});

		EditButton.setText("Edit");
		EditButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				EditButtonActionPerformed(evt);
			}
		});

		RemoveButton = new JButton();
		RemoveButton.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				databaseFacadeForListEditAndRemoveIngredientMenu.removeAdjacentRows();
			}
		});
		RemoveButton.setText("Remove");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 385, GroupLayout.PREFERRED_SIZE)
				.addGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
								.addGroup(Alignment.LEADING,
										layout.createSequentialGroup().addGap(8)
												.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 103,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addComponent(EditButton, GroupLayout.PREFERRED_SIZE, 103,
														GroupLayout.PREFERRED_SIZE)
												.addGap(18)
												.addComponent(RemoveButton, GroupLayout.PREFERRED_SIZE, 103,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(backbutton, GroupLayout.PREFERRED_SIZE, 103,
														GroupLayout.PREFERRED_SIZE))
								.addComponent(jScrollPane2, Alignment.LEADING, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addContainerGap(20, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addGap(123)
								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE)
								.addGap(0, 141, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addGap(23)
						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE).addGap(18)
						.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(28)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
								.addComponent(EditButton, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
								.addComponent(backbutton, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
								.addComponent(RemoveButton, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE))
						.addContainerGap(31, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
		setLocationRelativeTo(null);
	}

	/**
	 * Handles the action when the fetch button is clicked.
	 * 
	 * @param evt the action event
	 */
	public void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		databaseFacadeForListEditAndRemoveIngredientMenu.FetchData();
	}

	/**
	 * Handles the action when the back button is clicked.
	 * 
	 * @param evt the action event
	 */
	public void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {
		IngredientMenu ingredientMenu = new IngredientMenu();
		ingredientMenu.setVisible(true);
		this.dispose();

	}

	/**
	 * Handles the action when the edit button is clicked.
	 * 
	 * @param evt the action event
	 */
	public void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {
		databaseFacadeForListEditAndRemoveIngredientMenu.EditData();

	}

	
	/**
	 * Button to edit.
	 */
	public javax.swing.JButton EditButton;

	/**
	 * Button to navigate back.
	 */
	public javax.swing.JButton backbutton;

	/**
	 * Another button.
	 */
	public javax.swing.JButton jButton2;

	/**
	 * Label for information.
	 */
	public javax.swing.JLabel jLabel1;

	/**
	 * Another label for information.
	 */
	public javax.swing.JLabel jLabel2;

	/**
	 * Panel for UI.
	 */
	public javax.swing.JPanel jPanel1;

	/**
	 * Scroll pane for a table.
	 */
	public javax.swing.JScrollPane jScrollPane2;

	/**
	 * Table component.
	 */
	public javax.swing.JTable jTable2;

	/**
	 * Button to remove.
	 */
	public JButton RemoveButton;

	
}
