/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * The package com.turankanbur.calculator contains classes related to the calculator application.
 */
package com.turankanbur.calculator;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 * This class represents the GUI form for the ListMeal Menu.
 */
public class ListMealMenu extends javax.swing.JFrame {


	/**
	 * The serial version UID for serialization.
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * Facade for listing meals.
	 */
	DBFacadeListMeal databaseFacadeForListMealMenu;


	/**
	 * Constructor to initialize the ListMealMenu GUI.
	 */
	public ListMealMenu() {
		databaseFacadeForListMealMenu = new DBFacadeListMeal(this);
		setResizable(false);
		initComponents();
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mealbackground.jpg")));

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null }, { null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } },
				new String[] { "meal_id", "meal_name", "recipe_name", "meal_cost" }));
		jScrollPane1.setViewportView(jTable1);

		jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36));
		jLabel2.setText("Meal List");

		jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18));
		jButton1.setText("Fetch");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18));
		jButton3.setText("Back");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
				.createSequentialGroup()
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
						.createSequentialGroup().addGap(325)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(203).addComponent(jLabel2,
										GroupLayout.PREFERRED_SIZE, 209, GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(76).addComponent(jScrollPane1,
										GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(178)
										.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 96,
												GroupLayout.PREFERRED_SIZE)
										.addGap(83).addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 98,
												GroupLayout.PREFERRED_SIZE))))
						.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 330, GroupLayout.PREFERRED_SIZE))
				.addContainerGap(154, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(
						jPanel1Layout
								.createParallelGroup(
										Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(18)
										.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 54,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.UNRELATED)
										.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addGap(18)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 46,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 46,
														GroupLayout.PREFERRED_SIZE))
										.addContainerGap(87, Short.MAX_VALUE))
								.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 661, Short.MAX_VALUE));
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}

	/**
	 * Handles the action when the fetch button is clicked.
	 * 
	 * @param evt the action event
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		databaseFacadeForListMealMenu.FetchData();
	}

	/**
	 * Handles the action when the back button is clicked.
	 * 
	 * @param evt the action event
	 */
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		PlanMealMenu mealMenu = new PlanMealMenu();
		mealMenu.setVisible(true);
		this.dispose();
	}

	
	/**
	 * Button for action 1.
	 */
	public javax.swing.JButton jButton1;

	/**
	 * Button for action 3.
	 */
	public javax.swing.JButton jButton3;

	/**
	 * Label 2.
	 */
	public javax.swing.JLabel jLabel2;

	/**
	 * Label 3.
	 */
	public javax.swing.JLabel jLabel3;

	/**
	 * Panel 1.
	 */
	public javax.swing.JPanel jPanel1;

	/**
	 * Scroll pane 1.
	 */
	public javax.swing.JScrollPane jScrollPane1;

	/**
	 * Table 1.
	 */
	public javax.swing.JTable jTable1;

	
}
