/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * The package com.turankanbur.calculator contains classes related to the calculator application.
 */
package com.turankanbur.calculator;

import javax.swing.*;
import javax.swing.GroupLayout.Alignment;

import java.awt.Color;
import java.awt.event.KeyEvent;
import com.formdev.flatlaf.FlatDarculaLaf;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * This class represents the GUI form for the login menu.
 */
public class LoginMenu extends JFrame {

	/**
	 * The serial version UID for serialization.
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Username.
	 */
	String username;

	/**
	 * Password.
	 */
	String password;


	

	/**
	 * Facade for login.
	 */
	DBFacadeLogin userDatabaseFacadeForLogin;

	/**
	 * This class represents the GUI form for the login menu.
	 */
	public LoginMenu() {
		setResizable(false);
		setAutoRequestFocus(false);
		userDatabaseFacadeForLogin = new DBFacadeLogin();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	public void initComponents() {
		loginlabel = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		loginusername = new javax.swing.JTextArea();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		loginpassword = new javax.swing.JPasswordField();
		backtoregister = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		loginlabel.setFont(new java.awt.Font("Segoe UI", 1, 36));
		loginlabel.setText("LOGIN");

		loginusername.setColumns(20);
		loginusername.setRows(5);
		loginusername.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				loginusernameKeyTyped(evt);
			}
		});
		jScrollPane1.setViewportView(loginusername);

		jLabel3.setText("Username");

		jLabel4.setText("Password");

		loginpassword.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				loginpasswordKeyTyped(evt);
			}
		});

		backtoregister.setText("Back");
		backtoregister.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				backtoregisterMouseClicked(evt);
			}
		});
		backtoregister.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backtoregisterActionPerformed(evt);
			}
		});

		JPanel panel = new JPanel();
		panel.setBackground(new Color(13, 17, 23));

		btnLogin = new JButton();
		btnLogin.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				loginuser(username, password);
			}
		});
		btnLogin.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});
		btnLogin.setText("Login");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addComponent(panel, GroupLayout.PREFERRED_SIZE, 655, GroupLayout.PREFERRED_SIZE)
				.addGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
						.addGap(64)
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
										.addComponent(loginpassword).addComponent(jLabel4, Alignment.LEADING)
										.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 261,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel3, Alignment.LEADING))
								.addGroup(layout.createSequentialGroup()
										.addComponent(loginlabel, GroupLayout.PREFERRED_SIZE, 150,
												GroupLayout.PREFERRED_SIZE)
										.addGap(63))))
						.addGroup(layout.createSequentialGroup().addGap(128).addComponent(btnLogin,
								GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup().addGap(155).addComponent(backtoregister)))
				.addContainerGap(102, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(74).addComponent(loginlabel).addGap(41)
						.addComponent(jLabel3).addGap(27)
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
						.addGap(29).addComponent(jLabel4).addPreferredGap(ComponentPlacement.UNRELATED)
						.addComponent(loginpassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(30).addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
						.addGap(27).addComponent(backtoregister).addContainerGap(88, Short.MAX_VALUE))
				.addComponent(panel, GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE));
		panel.setLayout(null);

		JLabel lblNewLabel = new JLabel("");
		lblNewLabel.setIcon(new ImageIcon(getClass().getResource("/background.png")));
		lblNewLabel.setBounds(124, -89, 1302, 824);
		panel.add(lblNewLabel);
		getContentPane().setLayout(layout);

		pack();
		setLocationRelativeTo(null);
	}

	/**
	 * Handles key typing events in the login username field.
	 * 
	 * @param evt the key event
	 */
	public void loginusernameKeyTyped(KeyEvent evt) {
		username = loginusername.getText() + evt.getKeyChar();
	}

	/**
	 * Handles key typing events in the login password field.
	 * 
	 * @param evt the key event
	 */
	public void loginpasswordKeyTyped(KeyEvent evt) {
		char lastChar = evt.getKeyChar();
		char[] passwordChars = loginpassword.getPassword();
		char[] updatedPasswordChars = new char[passwordChars.length + 1];
		System.arraycopy(passwordChars, 0, updatedPasswordChars, 0, passwordChars.length);
		updatedPasswordChars[passwordChars.length] = lastChar;
		password = new String(updatedPasswordChars);
	}

	/**
	 * Handles the action when the back to register button is clicked.
	 * 
	 * @param evt the action event
	 */
	public void backtoregisterActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
		RegisterMenu registerMenu = new RegisterMenu();
		registerMenu.setVisible(true);
	}

	/**
	 * Handles the action when the back to register button is clicked with the
	 * mouse.
	 * 
	 * @param evt the mouse event
	 */
	public void backtoregisterMouseClicked(java.awt.event.MouseEvent evt) {
		RegisterMenu registermenu = new RegisterMenu();
		registermenu.setVisible(true);
		this.dispose();
	}

	
	 /**
     * @brief Creates and returns a MainMenu object.
     * 
     * This method initializes a new MainMenu object with the default configuration
     * and returns it.
     *
     * @return A new instance of MainMenu with the default configuration.
     */
	public MainMenu getMainMenu() {
		MainMenu mainMenu = new MainMenu("default");
		return mainMenu;
	}
	
	
	/**
	 * Logs in the user with the provided username and password.
	 * 
	 * @param username the username
	 * @param password the password
	 */
	public void loginuser(String username, String password) {
		if (userDatabaseFacadeForLogin.loginUser(username, password)) {
			MainMenu mainMenu = new MainMenu(username);
			mainMenu.setVisible(true);
			this.dispose();
		} else {
			// Handle login failure
		}
	}

	/**
	 * The main method to start the login menu GUI.
	 * 
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		FlatDarculaLaf.setup();
		UIManager.put("Button.arc", 999);
		SwingUtilities.invokeLater(() -> {
			LoginMenu loginMenu = new LoginMenu();
			loginMenu.setVisible(true);
			loginMenu.setResizable(false);
		});
	}

	/**
	 * Button to navigate back to the register screen.
	 */
	public javax.swing.JButton backtoregister;

	/**
	 * Label for the login section.
	 */
	public javax.swing.JLabel loginlabel;

	/**
	 * Label for displaying error messages or additional information during login.
	 */
	public javax.swing.JLabel jLabel3;

	/**
	 * Label for prompting the user to enter their username.
	 */
	public javax.swing.JLabel jLabel4;

	/**
	 * Panel for the login section.
	 */
	public javax.swing.JPanel jPanel1;

	/**
	 * Scroll pane for the login section.
	 */
	public javax.swing.JScrollPane jScrollPane1;

	/**
	 * Password field for entering the user's password during login.
	 */
	public javax.swing.JPasswordField loginpassword;

	/**
	 * Text area for entering the user's username during login.
	 */
	javax.swing.JTextArea loginusername;

	/**
	 * Label for displaying an image or logo related to the login section.
	 */
	public JLabel lblNewLabel;

	/**
	 * Button to initiate the login process.
	 */
	public JButton btnLogin;

}
