/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * The package com.turankanbur.calculator contains classes related to the calculator application.
 */
package com.turankanbur.calculator;

import java.awt.Dimension;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingUtilities;

/**
 * This class represents the GUI form for the MainMenu.
 */
public class MainMenu extends javax.swing.JFrame {

	/**
	 * The serial version UID for serialization.
	 */
	public static final long serialVersionUID = 1L;

	/**
	 * Constructor to initialize the MainMenu GUI.
	 * 
	 * @param username the current user's username
	 */
	public MainMenu(String username) {
		setResizable(false);
		initComponents();
		setUsername(username);
		setLocationRelativeTo(null);
	}

	/**
	 * Sets the username label.
	 * 
	 * @param username the current user's username
	 */
	public void setUsername(String username) {
		jLabel1.setText("Current User: " + username);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	public void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel1.setBounds(10, 11, 1390, 607);
		jLabel2 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		ingredientbutton = new javax.swing.JLabel();
		exitbutton = new javax.swing.JLabel();
		recipebutton = new javax.swing.JLabel();
		aboutbutton = new javax.swing.JLabel();
		mealsbutton = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newfoodbackground.png")));

		jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36));
		jLabel4.setForeground(new java.awt.Color(255, 102, 51));
		jLabel4.setText("RECIPE COST CALCULATOR MENU");

		ingredientbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ingredient.png")));
		ingredientbutton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				ingredientbuttonMouseClicked(evt);
			}

		});

		exitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png")));
		exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				exitbuttonMouseClicked(evt);
			}

		});

		recipebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipe.png")));
		recipebutton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				recipebuttonMouseClicked(evt);
			}

		});

		aboutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about.png")));
		aboutbutton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				aboutbuttonMouseClicked(evt);
			}

		});

		mealsbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meals.png")));
		mealsbutton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mealsbuttonMouseClicked(evt);
			}

		});
		getContentPane().setLayout(null);

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png")));
		jLabel1.setText("jLabel1");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
				.createSequentialGroup()
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap(329, Short.MAX_VALUE)
										.addComponent(ingredientbutton).addGap(150))
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
										.addComponent(recipebutton).addGap(191))
								.addGroup(Alignment.LEADING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 334,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)))
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(mealsbutton)
								.addGap(196)))
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addComponent(aboutbutton)
						.addComponent(exitbutton))
				.addGap(505))
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 975, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(405, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(171).addComponent(jLabel4).addContainerGap(647,
						Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING).addGroup(jPanel1Layout
				.createSequentialGroup()
				.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 282, GroupLayout.PREFERRED_SIZE)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup().addGap(7)
								.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
								.addGap(10).addComponent(ingredientbutton).addGap(22).addComponent(recipebutton)
								.addGap(20).addComponent(mealsbutton).addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
								.addContainerGap())
						.addGroup(jPanel1Layout.createSequentialGroup().addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(aboutbutton).addGap(18).addComponent(exitbutton).addGap(43)))));
		jPanel1.setLayout(jPanel1Layout);
		getContentPane().add(jPanel1);

		setSize(new Dimension(976, 668));
		setLocationRelativeTo(null);
	}

	/**
	 * Handles the action when the ingredient button is clicked.
	 * 
	 * @param evt the mouse event
	 */
	public void ingredientbuttonMouseClicked(java.awt.event.MouseEvent evt) {
		IngredientMenu ingredientmenu = new IngredientMenu();
		ingredientmenu.setVisible(true);
		this.dispose();
	}

	/**
	 * Handles the action when the exit button is clicked.
	 * 
	 * @param evt the mouse event
	 */
	public void exitbuttonMouseClicked(java.awt.event.MouseEvent evt) {
		JFrame frame = (JFrame) SwingUtilities.getRoot(this);
		if (frame != null) {
			frame.dispose();
		} else {
			System.exit(0);
		}
	}

	/**
	 * Handles the action when the recipe button is clicked.
	 * 
	 * @param evt the mouse event
	 */
	public void recipebuttonMouseClicked(java.awt.event.MouseEvent evt) {
		RecipeMenu recipeMenu = new RecipeMenu();
		recipeMenu.setVisible(true);
		this.dispose();
	}

	/**
	 * Handles the action when the about button is clicked.
	 * 
	 * @param evt the mouse event
	 */
	public void aboutbuttonMouseClicked(java.awt.event.MouseEvent evt) {
		String githubLink = "https://github.com/Eraytrn/ce205-final-project-eray-turan-doganay-kanbur-java";

		try {

			java.awt.Desktop.getDesktop().browse(java.net.URI.create(githubLink));
		} catch (java.io.IOException ex) {
			System.out.println(ex.getMessage());
		}

	}

	/**
	 * Handles the action when the meals button is clicked.
	 * 
	 * @param evt the mouse event
	 */
	public void mealsbuttonMouseClicked(java.awt.event.MouseEvent evt) {
		PlanMealMenu PlanMealMenu = new PlanMealMenu();
		PlanMealMenu.setVisible(true);
		this.dispose();
	}

	
	/**
	 * Label representing the "About" button.
	 */
	public javax.swing.JLabel aboutbutton;

	/**
	 * Label representing the "Exit" button.
	 */
	public javax.swing.JLabel exitbutton;

	/**
	 * Label representing the "Ingredient" button.
	 */
	javax.swing.JLabel ingredientbutton;

	/**
	 * Label representing the first generic label.
	 */
	public javax.swing.JLabel jLabel1;

	/**
	 * Label representing the second generic label.
	 */
	public javax.swing.JLabel jLabel2;

	/**
	 * Label representing the third generic label.
	 */
	public javax.swing.JLabel jLabel4;

	/**
	 * Panel containing various UI components.
	 */
	public javax.swing.JPanel jPanel1;

	/**
	 * Label representing the "Meals" button.
	 */
	public javax.swing.JLabel mealsbutton;

	/**
	 * Label representing the "Recipe" button.
	 */
	public javax.swing.JLabel recipebutton;

	
}