/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * The package com.turankanbur.calculator contains classes related to the calculator application.
 */
package com.turankanbur.calculator;

import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.GroupLayout;
import javax.swing.JButton;

/**
 * JFrame subclass for displaying the recipe menu interface.
 */
public class RecipeMenu extends javax.swing.JFrame {

	/**
	 * The serial version UID for serialization.
	 */
	private static final long serialVersionUID = 1L;

	
	/**
	 * Constructor to initialize the RecipeMenu GUI.
	 */
	public RecipeMenu() {
		setResizable(false);
		initComponents();
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setAutoscrolls(true);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipebackground.jpg")));

		jLabel2.setFont(new Font("Segoe UI", Font.BOLD, 24));
		jLabel2.setText("Recipe Menu");

		JButton btnNewButton = new JButton("Add Recipe");
		btnNewButton.setFocusPainted(false);
		btnNewButton.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				CreateRecipeMenu createrecipe = new CreateRecipeMenu();
				createrecipe.setVisible(true);
				dispose();
			}
		});
		btnNewButton.setFont(new Font("Tahoma", Font.BOLD, 16));
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});

		btnNewButton_1 = new JButton("Remove Recipe");
		btnNewButton_1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				RemoveRecipeMenu removerecipe = new RemoveRecipeMenu();
				removerecipe.setVisible(true);
				dispose();
			}
		});
		btnNewButton_1.setFont(new Font("Tahoma", Font.BOLD, 16));

		btnNewButton_2 = new JButton("List Recipe");
		btnNewButton_2.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				ListRecipeMenu listrecipe = new ListRecipeMenu();
				listrecipe.setVisible(true);
				dispose();
			}

		});
		btnNewButton_2.setFont(new Font("Tahoma", Font.BOLD, 16));
		btnNewButton_2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});

		btnNewButton_3 = new JButton("Back");
		btnNewButton_3.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				String username = " ";
				MainMenu mainmenu = new MainMenu(username);
				mainmenu.setVisible(true);
				dispose();
			}
		});
		btnNewButton_3.setFont(new Font("Tahoma", Font.BOLD, 16));
		btnNewButton_3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
				.createSequentialGroup()
				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 437, GroupLayout.PREFERRED_SIZE)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING).addGroup(jPanel1Layout
						.createSequentialGroup().addGap(77)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 202,
												GroupLayout.PREFERRED_SIZE)
										.addGap(32).addComponent(btnNewButton_2, GroupLayout.PREFERRED_SIZE, 202,
												GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(btnNewButton_1, GroupLayout.PREFERRED_SIZE, 202,
												GroupLayout.PREFERRED_SIZE)
										.addGap(32).addComponent(btnNewButton_3, GroupLayout.PREFERRED_SIZE, 202,
												GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(37, Short.MAX_VALUE))
						.addGroup(jPanel1Layout.createSequentialGroup().addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 316, GroupLayout.PREFERRED_SIZE)
								.addGap(39)))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 513, Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(83).addGroup(jPanel1Layout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(35)
								.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
								.addGap(21).addComponent(btnNewButton_1, GroupLayout.PREFERRED_SIZE, 140,
										GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(34)
								.addComponent(btnNewButton_2, GroupLayout.PREFERRED_SIZE, 140,
										GroupLayout.PREFERRED_SIZE)
								.addGap(23).addComponent(btnNewButton_3, GroupLayout.PREFERRED_SIZE, 140,
										GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(93, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(28)
						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(429, Short.MAX_VALUE)));
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
		setLocationRelativeTo(null);
	}

	
	/**
	 * JLabel for displaying text or an image.
	 */
	public javax.swing.JLabel jLabel1;

	/**
	 * Another JLabel for displaying text or an image.
	 */
	public javax.swing.JLabel jLabel2;

	/**
	 * JPanel for organizing and grouping components.
	 */
	public javax.swing.JPanel jPanel1;

	/**
	 * JButton for triggering an action.
	 */
	public JButton btnNewButton;

	/**
	 * Another JButton for triggering an action.
	 */
	public JButton btnNewButton_1;

	/**
	 * Another JButton for triggering an action.
	 */
	public JButton btnNewButton_2;

	/**
	 * Another JButton for triggering an action.
	 */
	public JButton btnNewButton_3;

	
}
