/**
 * The package com.turankanbur.calculator contains classes related to the calculator application.
 */
package com.turankanbur.calculator;

import javax.swing.*;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;

/**
 * This class represents the registration menu for the application.
 */
public class RegisterMenu extends JFrame {

	/**
	 * The serial version UID for serialization.
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * The database facade for register.
	 */
	private DBFacaderRegister userDatabaseFacadeForRegister;
	
	/**
	 * Observer for password validation.
	 */
	PswrdValidObserver observer;


	/**
	 * Constructor to initialize the RegisterMenu GUI.
	 */
	public RegisterMenu() {
		setResizable(false);
		userDatabaseFacadeForRegister = new DBFacaderRegister();
		userDatabaseFacadeForRegister.createUserTable();
		initComponents();
		setLocationRelativeTo(null);
	}

	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	public void initComponents() {
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setBounds(762, 39, 150, 48);
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setBounds(697, 98, 169, 14);
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setBounds(697, 217, 179, 14);
		jPasswordField1 = new javax.swing.JPasswordField();
		jPasswordField1.setBounds(697, 242, 261, 20);
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setBounds(713, 452, 88, 16);
		jButton1 = new javax.swing.JButton();
		jButton1.setBounds(819, 450, 79, 23);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setAutoRequestFocus(false);
		setBackground(new java.awt.Color(13, 17, 23));

		jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36));
		jLabel2.setText("SIGN UP");

		jLabel3.setText("Username");

		jLabel4.setText("Password");

		jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jPasswordField1KeyTyped(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12));
		jLabel5.setText("I've an account ");

		jButton1.setText("Login");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton1MouseClicked(evt);
			}
		});
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		getContentPane().setLayout(null);
		getContentPane().add(jLabel2);
		getContentPane().add(jLabel3);
		getContentPane().add(jLabel4);
		getContentPane().add(jPasswordField1);
		getContentPane().add(jLabel5);
		getContentPane().add(jButton1);

		usernameField = new JTextField();
		usernameField.setBounds(697, 123, 261, 20);
		getContentPane().add(usernameField);
		usernameField.setColumns(10);

		JPanel panel = new JPanel();
		panel.setBackground(new Color(13, 17, 23));
		panel.setBounds(0, 0, 653, 523);
		getContentPane().add(panel);
		panel.setLayout(null);

		JLabel lblNewLabel = new JLabel("");
		lblNewLabel.setBounds(123, 123, 373, 412);
		panel.add(lblNewLabel);
		lblNewLabel.setIcon(new ImageIcon(getClass().getResource("/background.png")));

		JLabel warningLabel = new JLabel("");
		warningLabel.setBounds(697, 305, 261, 25);
		getContentPane().add(warningLabel);

		observer = new PswrdValidObserver(jPasswordField1, warningLabel);

		JLabel jLabel7 = new JLabel("Email");
		jLabel7.setBounds(697, 161, 46, 14);
		getContentPane().add(jLabel7);

		textField = new JTextField();
		textField.setBounds(697, 186, 261, 20);
		getContentPane().add(textField);
		textField.setColumns(10);

		JLabel jLabel8 = new JLabel("Confirm Password");
		jLabel8.setBounds(697, 280, 150, 14);
		getContentPane().add(jLabel8);

		textField_1 = new JTextField();
		textField_1.setBounds(697, 310, 261, 20);
		getContentPane().add(textField_1);
		textField_1.setColumns(10);

		registerbutton = new JButton();
		registerbutton.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				String username = usernameField.getText();
				String password = new String(jPasswordField1.getPassword());
				String email = textField.getText();
				String confirmPassword = textField_1.getText();
				DBFacaderRegister userDatabaseFacadeForRegister = new DBFacaderRegister();
				userDatabaseFacadeForRegister.addUserToDatabase(username, password, confirmPassword, email);
			}
		});
		registerbutton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});
		registerbutton.setText("Register");
		registerbutton.setBounds(784, 357, 108, 48);
		getContentPane().add(registerbutton);
		jPasswordField1.getDocument().addDocumentListener(observer);
		setSize(new Dimension(1070, 562));
		setLocationRelativeTo(null);
	}

	/**
	 * Handles the key typed event on the password field.
	 * 
	 * @param evt the key event
	 */
	public void jPasswordField1KeyTyped(KeyEvent evt) {

	}

	/**
	 * Handles the mouse clicked event on the login button.
	 * 
	 * @param evt the mouse event
	 */
	public void jButton1MouseClicked(MouseEvent evt) {
		LoginMenu loginMenu = new LoginMenu();
		loginMenu.setVisible(true);
		this.dispose();
	}

	/**
	 * Handles the action performed event on the login button.
	 * 
	 * @param evt the action event
	 */
	public void jButton1ActionPerformed(ActionEvent evt) {

	}

	/**
	 * Button for registration.
	 */
	public javax.swing.JButton registerbutton;

	/**
	 * Field for entering the username.
	 */
	public JTextField usernameField;

	/**
	 * Field for entering the email.
	 */
	public JTextField textField;

	/**
	 * Field for entering the confirm password.
	 */
	public JTextField textField_1;

	/**
	 * Field for entering the password.
	 */
	public javax.swing.JPasswordField jPasswordField1;

	/**
	 * Label for displaying warnings.
	 */
	public javax.swing.JLabel warningLabel;

	/**
	 * Label for "I've an account".
	 */
	public javax.swing.JLabel jLabel5;

	/**
	 * Label for "Confirm Password".
	 */
	public javax.swing.JLabel jLabel4;

	/**
	 * Label for "Email".
	 */
	public JLabel jLabel3;

	/**
	 * Label for "Username".
	 */
	public javax.swing.JLabel jLabel2;

	/**
	 * Button for redirecting to the login menu.
	 */
	public javax.swing.JButton jButton1;

}
